# Generated by Django 3.2.9 on 2021-11-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('post_data', models.DateField(auto_now=True)),
                ('good', models.IntegerField(blank=True, default=0, null=True)),
                ('interest', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
